= Enterprise Integration Patterns

== List of Patterns
* `Aggregator` How do we combine the results of individual but related messages so that they can be processed as a whole?
* `Canonical Data Model` How can you minimize dependencies when integrating applications that use different data formats?
* `Channel Adapter` How can you connect an application to the messaging system so that it can send and receive messages?
* `Channel Purger` How can you keep leftover messages on a channel from disturbing tests or running systems?
* `Claim Check` How can we reduce the data volume of message sent across the system without sacrificing information content?
* `Command Message` How can messaging be used to invoke a procedure in another application?
* `Competing Consumers` How can a messaging client process multiple messages concurrently?
* `Composed Message Processor` How can you maintain the overall message flow when processing a message consisting of multiple elements, each of which may require different processing?
* `Content Enricher` How do we communicate with another system if the message originator does not have all the required data items available?
* `Content Filter` How do you simplify dealing with a large message when you are interested only in a few data items?
* `Content-Based Router` How do we handle a situation in which the implementation of a single logical function is spread across multiple physical systems?
* `Control Bus` How can we effectively administer a messaging system that is distributed across multiple platforms and a wide geographic area?
* `Correlation Identifier` How does a requestor that has received a reply know which request this is the reply for?
* `Datatype Channel` How can the application send a data item such that the receiver will know how to process it?
* `Dead Letter Channel` What will the messaging system do with a message it cannot deliver?
* `Detour` How can you route a message through intermediate steps to perform validation, testing, or debugging functions?
* `Document Message` How can messaging be used to transfer data between applications?
* `Durable Subscriber` How can a subscriber avoid missing messages while it’s not listening for them?
* `Dynamic Router` How can you avoid the dependency of the router on all possible destinations while maintaining its efficiency?
* `Envelope Wrapper` How can existing systems participate in a messaging exchange that places specific requirements, such as message header fields or encryption, on the message format?
* `Event Message` How can messaging be used to transmit events from one application to another?
* `Event-Driven Consumer` How can an application automatically consume messages as they become available?
* `File Transfer` How can I integrate multiple applications so that they work together and can exchange information?
* `Format Indicator` How can a message’s data format be designed to allow for possible future changes?
* `Guaranteed Delivery` How can the sender make sure that a message will be delivered even if the messaging system fails?
* `Idempotent Receiver` How can a message receiver deal with duplicate messages?
* `Invalid Message Channel` How can a messaging receiver gracefully handle receiving a message that makes no sense?
* `Message Broker` How can you decouple the destination of a message from the sender and maintain central control over the flow of messages?
* `Message Bus` What architecture enables separate applications to work together but in a decoupled fashion such that applications can be easily added or removed without affecting the others?
* `Message Channel` How does one application communicate with another using messaging?
* `Message Dispatcher` How can multiple consumers on a single channel coordinate their message processing?
* `Message Endpoint` How does an application connect to a messaging channel to send and receive Messages?
* `Message Expiration` How can a sender indicate when a message should be considered stale and thus shouldn’t be processed?
* `Message Filter` How can a component avoid receiving uninteresting messages?
* `Message History` How can we effectively analyze and debug the flow of messages in a loosely coupled system?
* `Message Router` How can you decouple individual processing steps so that messages can be passed to different filters depending on a set of conditions?
* `Message Sequence` How can messaging transmit an arbitrarily large amount of data?
* `Message Store` How can we report against message information without disturbing the loosely coupled and transient nature of a messaging system?
* `Message Translator` How can systems using different data formats communicate with each other using messaging?
* `Message` How can two applications connected by a message channel exchange a piece of information?
* `Messaging Bridge` How can multiple messaging systems be connected so that messages available on one are also available on the others?
* `Messaging Gateway` How do you encapsulate access to the messaging system from the rest of the application?
* `Messaging Mapper` How do you move data between domain objects and the messaging infrastructure while keeping the two independent of each other?
* `Messaging` How can I integrate multiple applications so that they work together and can exchange information?
* `Normalizer` How do you process messages that are semantically equivalent but arrive in a different format?
* `Pipes and Filters` How can we perform complex processing on a message while maintaining independence and flexibility?
* `Point-to-Point Channel` How can the caller be sure that exactly one receiver will receive the document or perform the call?
* `Polling Consumer` How can an application consume a message when the application is ready?
* `Process Manager` How do we route a message through multiple processing steps when the required steps may not be known at design time and may not be sequential?
* `Publish-Subscribe Channel` How can the sender broadcast an event to all interested receivers?
* `Recipient List` How do we route a message to a dynamic list of recipients?
* `Remote Procedure Invocation` How can I integrate multiple applications so that they work together and can exchange information?
* `Request-Reply` When an application sends a message, how can it get a response from the receiver?
* `Resequencer` How can we get a stream of related but out-of-sequence messages back into the correct order?
* `Return Address` How does a replier know where to send the reply?
* `Routing Slip` How do we route a message consecutively through a series of processing steps when the sequence of steps is not known at design time and may vary for each message?
* `Scatter-Gather` How do you maintain the overall message flow when a message must be sent to multiple recipients, each of which may send a reply?
* `Selective Consumer` How can a message consumer select which messages it wishes to receive?
* `Service Activator` How can an application design a service to be invoked both via various messaging technologies and via non-messaging techniques?
* `Shared Database` How can I integrate multiple applications so that they work together and can exchange information?
* `Smart Proxy` How can you track messages on a service that publishes reply messages to the Return Address specified by the requestor?
* `Splitter` How can we process a message if it contains multiple elements, each of which may have to be processed in a different way?
* `Test Message` What happens if a component is actively processing messages but garbles outgoing messages due to an internal fault?
* `Transactional Client` How can a client control its transactions with the messaging system?
* `Wire Tap` How do you inspect messages that travel on a Point-to-Point Channel?
