= Python Unit Testing Framework

builtin unittest library

== Test Case
[source,python]
.example
----
class TestStringMethods(unittest.TestCase):

    def test_upper(self):
        self.assertEqual('foo'.upper(), 'FOO')

    def test_isupper(self):
        self.assertTrue('FOO'.isupper())
        self.assertFalse('Foo'.isupper())
----

*Key Notes*

* class inherited unittest.TestCase
* class name start with `Test`
* test method name start with `test_*`

=== Hook Methods
* setUp(self)
* tearDown(self)
* setUpClass()
+
[source,python]
----
@classmethod
def setUpClass(cls):
    ...
----
* tearDownClass()
+
[source,python]
----
@classmethod
def tearDownClass(cls):
    ...
----
* addCleanup(function, /, *args, **kwargs) +
Add a function to be called after tearDown() to cleanup resources used during the test.

* doCleanups() +
This method is called unconditionally after tearDown(), or after setUp() if setUp() raises an exception.

* classmethod addClassCleanup(function, /, *args, **kwargs) +
Add a function to be called after tearDownClass() to cleanup resources used during the test class.

* classmethod doClassCleanups() +
This method is called unconditionally after tearDownClass(), or after setUpClass() if setUpClass() raises an exception.

=== Assertion

|===
|Assertion |Description

|assertEqual()
|

|assertNotEqual()
|

|assertRaises()
|verify that a specific exception gets raised

|@unittest.expectedFailure
|Mark the test as an expected failure or error.
|===

=== Run Tests
.CLI
[source,bash]
----
# run test with higher verbosity
python -m unittest -v

python -m unittest
----

.Programmatically
[source,python]
----
# run test with higher verbosity
if __name__ == '__main__':
    unittest.main()
----

=== Test Suite
[source,python]
----
def suite():
    suite = unittest.TestSuite()
    suite.addTest(WidgetTestCase('test_default_widget_size'))
    suite.addTest(WidgetTestCase('test_widget_resize'))
    return suite

if __name__ == '__main__':
    runner = unittest.TextTestRunner()
    runner.run(suite())
----

=== Skip Tests
* decorator
  ** `@unittest.skip`
  ** `@unittest.skipIf`
  ** `@unittest.skipUnless`
* instance method
  ** `self.skipTest()`

[source,python]
.example
----
class MyTestCase(unittest.TestCase):

    @unittest.skip("demonstrating skipping")
    def test_nothing(self):
        self.fail("shouldn't happen")

    @unittest.skipIf(mylib.__version__ < (1, 3),
                     "not supported in this library version")
    def test_format(self):
        # Tests that work for only a certain version of the library.
        pass

    @unittest.skipUnless(sys.platform.startswith("win"), "requires Windows")
    def test_windows_support(self):
        # windows specific testing code
        pass

    def test_maybe_skipped(self):
        if not external_resource_available():
            self.skipTest("external resource not available")
        # test code that depends on the external resource
        pass
----